modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/bl4ckscor3/UnnamedSculkMod/issues"

[[mods]]
	modId="unnamedsculkmod"
	version="${file.jarVersion}"
	displayName="UnnamedSculkMod"
	displayURL="https://insert.curseforge.link.here"
	authors="bl4ckscor3, Redstone_Dubstep"
	description='''An as yet unnamed mod involving sculk.'''

[[dependencies.unnamedsculkmod]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unnamedsculkmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
