modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/bl4ckscor3/SculkTransporting/issues"

[[mods]]
	modId="sculktransporting"
	version="${file.jarVersion}"
	displayName="Sculk Transporting"
	displayURL="https://insert.curseforge.link.here"
	authors="bl4ckscor3, Redstone_Dubstep"
	description='''A mod adding an item transport solution involving sculk.'''

[[dependencies.sculktransporting]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sculktransporting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
