modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://github.com/bl4ckscor3/SculkTransporting/issues"

[[mods]]
	modId="sculktransporting"
	version="${file.jarVersion}"
	displayName="Sculk Transporting"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/sculk-transporting/"
	authors="bl4ckscor3, Redstone_Dubstep"
	description='''A mod adding an item transport solution involving sculk.'''

[[dependencies.sculktransporting]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sculktransporting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
